### ISSUE TITLE
bug: createPublicClient

### ISSUE THREAD

**Issue by cryptofast-dev** [wagmi-dev/viem#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.11

### Current Behavior

![image](https://github.com/wagmi-dev/viem/assets/137076090/1ee41ca3-92ad-462b-bc42-07494629a013)

Since the last update, createPublicClient stopped working in my app.

This is my code:

```
const client = createPublicClient({
           chain: getWagmiChain(network.networkData.chainId),
           transport: http(),
         });

         if (client) {
           const addressContract: `0x${string}` = `0x${(isMain
             ? mainContract_address
             : address
           ).substring(2, (isMain ? mainContract_address : address).length)}`;

           const gas = await client.estimateContractGas({
             account: `0x${user.address.substring(2, user.address.length)}`,
             address: addressContract,
             abi: isMain ? mainContract_abi : ercContract_abi,
             functionName,
             chainId,
             args: [...args],
             price,
           });

           const gasLimit = 25000 + Number(gas);
           return gasLimit;
         } else {
           return false;
         }
```

### Expected Behavior

It was working perfectly until yesterday and today I get the following error:

Type error: Property 'estimateContractGas' does not exist on type 'never'.

**Comment by jxom** [comment]
Can you try upgrade to TypeScript >=5.1

**Comment by cryptofast-dev** [comment]
![image](https://github.com/wagmi-dev/viem/assets/137076090/4c799641-cd63-41fe-a2a5-1bc1e58ec136)

It's upgraded.
The problem remains exactly the same.
With the last update I had to modify the wagmi configuration, it was like this:

```
import { configureChains, createConfig, mainnet } from "wagmi";
import { avalancheFuji, bscTestnet, goerli, polygonMumbai } from "wagmi/chains";

import {
   EthereumClient,
   w3mConnectors,
   w3mProvider,
} from "@web3modal/ethereum";

const chains = [mainnet, goerli, bscTestnet, polygonMumbai, avalancheFuji];

const { publicClient } = configureChains(chains, [
   w3mProvider({ projectId: process.env.NEXT_PUBLIC_WC_KEY }),
   // infuraProvider({ apiKey: process.env.NEXT_PUBLIC_INFURA_KEY }),
]);

export const config = createConfig({
   autoConnect: true,
   connectors: w3mConnectors({
     projectId: process.env.NEXT_PUBLIC_WC_KEY,
     chains,
   }),
   publicClient,
});

const ethereumClient = new EthereumClient(config, chains);

export { chains, ethereumClient };
```

Before, it used websocketPublicClient but it also throws an error after upgrading.

When removing websocketPublicClient I also get this error that you commented above.
I don't know if it has something to do with it, until yesterday it was working excellent.

**Comment by jxom** [comment]
To confirm, everything works okay with 1.2.10? 
Will take a look.

**Comment by cryptofast-dev** [comment]
I just reverted some changes to understand when the error starts.

- web3modal/ethereum and web3modal/react are updated to the latest version (^2.6.2)

- wagmi is also updated to the latest version (^1.3.8)

- viem is updated, now, at ^1.2.10

Everything works correctly.
This is my setup with viem 1.2.10:

```
import { configureChains, createConfig, mainnet } from "wagmi";
import { avalancheFuji, bscTestnet, goerli, polygonMumbai } from "wagmi/chains";

import {
   EthereumClient,
   w3mConnectors,
   w3mProvider,
} from "@web3modal/ethereum";

const chains = [mainnet, goerli, bscTestnet, polygonMumbai, avalancheFuji];

const { publicClient, webSocketPublicClient } = configureChains(chains, [
   w3mProvider({ projectId: process.env.NEXT_PUBLIC_WC_KEY }),
   // infuraProvider({ apiKey: process.env.NEXT_PUBLIC_INFURA_KEY }),
]);

export const config = createConfig({
   autoConnect: true,
   connectors: w3mConnectors({
     projectId: process.env.NEXT_PUBLIC_WC_KEY,
     chains,
   }),
   publicClient,
   webSocketPublicClient,
});

const ethereumClient = new EthereumClient(config, chains);

export { chains, ethereumClient };
```

and I use the function estimateGasContract to estimate the gas fee of the transaction in the network that the user wants to use, but the gas is estimated even if the user is not positioned in that network, that is why I use viem and not wagmi's publicClient.

When updating viem to 1.2.11, I get both errors:

- I can no longer use webSocketPublicClient in the config, I get this error:

```
Type '({ chainId }: { chainId?: number; }) => undefined' is not assignable to type '(config: { chainId?: number; }) => never'.
   Type 'undefined' is not assignable to type 'never'.ts(2322)
index.d.ts(50, 5): The expected type comes from property 'webSocketPublicClient' which is declared here on type 'CreateConfigParameters<never, never>'
```

- I can't use estimateContactGas anymore, the error I get is the one mentioned above:

`Property 'estimateContractGas' does not exist on type 'never'`

**Comment by jxom** [comment]
Might also be helpful to provide a minimal reproduction on https://www.typescriptlang.org/play so it’s easier for us to debug.

**Comment by cryptofast-dev** [comment]
Create a new project and try adding viem + wagmi + web3modal + typescript with nextjs. It worked perfectly.
Reviewing differences between projects, I found the error.
In my project I am using strict=false in tsconfig.json
In the new project strict is true and it works.
I change strict to true in my main project, and everything is fixed, but I have other typescript "errors" in the code because of the strict check, which prevents me from building the application.

It's weird, since with non-strict checking you shouldn't get an error that doesn't show up when you're not in strict mode.

Is there a solution that would allow me to keep my strict false or do I have to refactor all my code to make it work despite the typescript being strict on checks?

**Comment by jxom** [comment]
Ah yes, that’ll do it. We recommend for projects to turn strict mode on, see: https://viem.sh/docs/typescript.html. Understand that this might be a pain for other errors that may arise in your project, but we definitely think it’s worthwhile to have it on (you can probably `// @ts-expect-error` if you wish to incrementally migrate to strict mode).
